### ISSUE TITLE
Missing $single->ID value in template loop

### ISSUE THREAD

**Issue by css117** [picandocodigo/List-Category-Posts#167] opened 2015-06-10 13:58 UTC
Hello,
when testing a new widget template, I needed to use the post ID from this loop :

`foreach ($this->catlist->get_categories_posts() as $single){`

$single indeed has a fisrt property called ID, but `$single->ID` is empty.

I managed this from the `$single->guid`, but it should be more convenient to use it form the `$single->ID` property

Thanks in advance !

**Comment by zymeth25** [comment] 2018-02-09 10:41
I cannot reproduce this, `catlist->get_categories_posts()` works in templates without a problem. Besides, if the WP_Post instance has no ID property it means something is wrong with WordPress, not this plugin.

**Comment by picandocodigo** [comment] 2018-02-12 20:53
Closing since it's an ancient issue and the code has changed so much since then.

**Closed by picandocodigo** 2018-02-12 20:53 UTC
