### ISSUE TITLE
Tag starting_with allowing OR

### ISSUE THREAD

**Issue by bingokid** [picandocodigo/List-Category-Posts#116] opened 2014-07-24 11:31 UTC
starting_with="a" will return all posts with titles starting with letter A

Would it be possible to display titles with more different starting letters, for instance display posts starting with a,b,c,d,e,f,g

Tnx

**Comment by MaxDeFa** [comment] 2015-01-19 11:02
Thi feature doesn't work :(

**Comment by picandocodigo** [comment] 2015-01-19 17:28
@MaxDeFa this should work on version 0.53 and forward. What shortcode are you using?

**Comment by MaxDeFa** [comment] 2015-01-20 08:59
For example, this:
[catlist name=movietv starting_with="l"]
(whit or whitout ", ', uppercase, etc.) 

I tried other features (orderby, order, numberpost, pagination...) and work fine.
The only that doesn't is starting_with :(

Massimo

**Comment by MaxDeFa** [comment] 2015-01-20 09:00
BTW, my plugin version is 0.53, of course ^__^

Massimo

**Comment by picandocodigo** [comment] 2015-01-22 18:41
@MaxDeFa I'm refactoring lots of code at the moment. I can't reproduce your issue though, using something like:
`[catlist name=1 starting_with="l,m"]`
Or even:
`[catlist name=1 starting_with="l,m"]`
Works for me.
What does the plugin show when you use:
` [catlist name=movietv]`
And what does it show when using:
`[catlist starting_with="l"]`
?

Thanks!

**Comment by MaxDeFa** [comment] 2015-01-24 12:26
With
[catlist name=16 starting_with="l,m"] 
or
[catlist name=movietv starting_with="l,m"]
plugin shows nothing..
("movietv" is tem_id 16 in wp_terms table) 

With
[catlist name=movietv] 
pugin shows the last 10 post of category "movietv".

With
[catlist name=16]
or with
[catlist starting_with="l"] 
pugin shows nothing.

Massimo

**Comment by MaxDeFa** [comment] 2015-01-24 12:32
Errata corrige:
with
`[catlist name=16]`
plugin shows something: last 10 post, but from all categories not from category 16 (movietv)

Plugin version now is 0.54.1

Massimo

**Comment by MaxDeFa** [comment] 2015-03-08 11:44
Nothing new about this feature?

**Comment by picandocodigo** [comment] 2015-03-09 09:47
I'll see if I can set some time for the plugin this week and I'll check this out. Thanks.

**Comment by diegosf93** [comment] 2015-04-07 02:41
@MaxDeFa What version of Wordpress you have ???

**Comment by MaxDeFa** [comment] 2015-04-07 07:58
@diegosf93 I have the last one, 4.1.1.

**Comment by diegosf93** [comment] 2015-04-08 00:44
@MaxDeFa And plugin version 0.54.1? You tried with the last one ?

**Comment by MaxDeFa** [comment] 2015-04-08 08:29
@diegosf93 Of course, I tried with every update, from 0.53 to present (0.58.1), but nothing change.

This test works (last 10 post from category movietv/16):
`[catlist name=movietv]`

This works wrong (it displays last 10 post, yes, but from all categories, not from movietv/16):
`[catlist name=16]`

These don't work (nothing displayed)
`[catlist name=movietv starting_with="L"]`
`[catlist name="movietv" starting_with="L"]`
`[catlist name=movietv starting_with=l]`
`[catlist name="movietv" starting_with="l"]`
`[catlist name=16 starting_with="L"]`
`[catlist name="16" starting_with="L"]`
`[catlist name=16 starting_with=l]`
`[catlist name="16" starting_with="l"]`

**Comment by diegosf93** [comment] 2015-04-09 23:26
Im working in that !

**Comment by diegosf93** [comment] 2015-04-10 02:10
@picandocodigo Hi Fernando, I have a question with the examples  of  @MaxDeFa what happens If he has posts with movietv category but they dont start with L ??? Or it have to show Posts that start with L and have category movietv?

**Comment by bongsaculles** [comment] 2015-10-09 07:19
Hi, please allow me to join this thread as I have the same issue with the STARTING_WITH parameter. It also doesn't work with me, and all other CATLIST shortcakes in the same page stop working when I use STARTING_WITH in at least one of them.

In a similar manner the parameter TAGS also does not work.

I am using the latest version of the plug-in as well as the latest version of WP. My WP theme is ACCELERATE.

I've seen this issue in wordpress.org support for quite some time now. I think the first time somebody brought this up was 2 years ago. But no resolution was ever arrived at.

**Comment by bongsaculles** [comment] 2015-10-09 07:29
HI, these are screenshots I took to show/illustrate the issues I encountered in using the STARTING_WITH and TAGS parameters of CATLIST.

![catlist test code](https://cloud.githubusercontent.com/assets/15045639/10388179/4e6b2e64-6e9a-11e5-93f5-9d139760b311.jpg)
![catlist test output](https://cloud.githubusercontent.com/assets/15045639/10388180/4edebf46-6e9a-11e5-9495-96e651c55efd.jpg)

**Comment by zymeth25** [comment] 2018-09-04 17:34
As of now `starting_with` runs without problems. Issues descibed above were almost certainly caused by bugs fixed in #289 and #316.

Issue can be closed.

**Closed** 2018-09-04 19:13 UTC
Labels: new-feature
