### ISSUE TITLE
Question: List all Posts with an already existing templae

### ISSUE THREAD

**Issue by Mannshoch** [picandocodigo/List-Category-Posts#197] opened 2016-04-14 08:42 UTC
Sorry for asking if already answered.

I trying since hours to get catlist work as wished. At moment I have a template that work for a Site and punblish every Post. If I use it with Catlist and no change of styling happened.

[catlist template=startcategory id=13 thumbnail=yes content=yes ]

wp-content/themes/own/startcategory.php

```
<?php /*
Template Name: CategoryBlog
*/ ?>

<?php get_header(); ?>

<?php $latest = new WP_Query('showposts=10'); $postCount = 0; ?>

<div id="content">
<div id="main">

    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
    <h1><?php the_title(); ?></h1>
        <?php the_content(); ?>
    <?php endwhile; else: endif; ?>

    <?php query_posts('category_name='.get_the_title().'&post_status=publish,future');?>
    <?php if ( have_posts() ) : while ( have_posts() ) : the_post(); ?>
        <?php if(has_post_thumbnail()) { $thumb = wp_get_attachment_image_src(get_post_thumbnail_id(), 'medium'); } 
    $postCount = $postCount+1;
    ?>  
        <li>
        <article id="post-<?php the_ID(); ?>" <?php post_class(array('placeholder')); ?>>
            <div class="post-main row">
                <aside class="post-image col-sm-3" style="background-image:url(<?php echo $thumb[0]; ?>);">
                    <a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>">
                        <img src="<?php echo get_template_directory_uri(); ?>/img/maske.png" class="img-responsive">
                    </a>
                </aside>
                <section class="col-sm-8">
                    <h4 class="main-title">
                        <a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>"><?php the_title(); ?></a>
                    </h4>
                    <p><small>Von <?php echo get_the_author();?>, <?php echo get_the_date( 'j.F.Y' ); ?></small></p>
                    <p class="main-content">
                        <?php the_excerpt(); ?>
                    </p>
                </section>
            </div>
        </article>
    </li>
    <?php if ($latest->current_post +1 !== $latest->post_count) { echo('<hr class="col-sm-8 col-sm-offset-3">'); } ?>
    <?php endwhile; else: endif; ?>
</div>
</div>

<?php get_footer(); ?>
```

**Comment by Mannshoch** [comment] 2016-04-18 10:46
If possible please help me.

**Comment by zymeth25** [comment] 2018-02-09 11:47
Hi @Mannshoch , the problem is you misunderstood how the `template` parameter works. It has nothing to do with theme templates, it requires you to create a special template with a very specific syntax that the LCP plugin understands. Please read the documentation first before opening an issue, the template system is described [here](https://github.com/picandocodigo/List-Category-Posts/wiki/Template-System).

**Comment by Mannshoch** [comment] 2018-02-09 18:58
Thanks for your Answer. This Ticket from 2016 is finally out-of-date and could be closed.

**Comment by zymeth25** [comment] 2018-02-09 18:59
Feel free to close it then :wink: I started contributing to the plugin just recently so thought it would be a good idea to go through the issues.

**Closed** 2018-02-09 19:08 UTC

**Comment by Mannshoch** [comment] 2018-02-09 19:11
Thats a really good Idea to go through all issues. 

Thanks for your Work then.
