### ISSUE TITLE
Templates are broken again with the newly added loop fix

### ISSUE THREAD

**Issue by wimstefan** [picandocodigo/List-Category-Posts#165] opened 2015-06-10 12:22 UTC
I copied the default template to <my_theme>list-category-posts/ and made some minor change (just adding a star in front of every list element). That used to work until the version 0.62 where all in a sudden I only get 1 item in the list ... :-/

Not sure if that's enough information provided ... I'm happy to answer any question for more information.

Thanks for your efforts!

**Comment by Sophist-UK** [comment] 2015-06-10 15:11
@wimstefan - I assume that you have NOT just tried to copy one file from a version to overwrite the same file from an earlier version - but that you have installed 0.62 and it stopped working without any of your minor changes.

As the author of the loop changes, I can only apologise - all I can say is that they worked on my site when I tested them.

We will need @picandocodigo to revert them and for him to take a look at why they might be failing.

**Comment by picandocodigo** [comment] 2015-06-10 15:54
@wimstefan I tested @Sophist-UK's new code with templates and it worked out. What shortcode are you using? So I can reproduce the issue and try to figure out what's going on. Thanks!

**Comment by wimstefan** [comment] 2015-06-10 16:26
Hi all - I installed 0.62 and copied the new templates/default.php to my list-category-posts/list.php and changed line 57 to the following:
$lcp_display_output .= "&#9733;&nbsp;&nbsp;";

The shortcode I'm using is:
[catlist id=4,5,42 template=list numberposts=10 year=2015 orderby=id excludeposts=this,881,1039]

I hope that information is of any help ...

**Comment by irvingarroyo** [comment] 2015-07-27 16:21
Same problem...
[catlist template="starredcategory" categorypage="yes" numberposts="5" pagination="yes" excerpt="yes" excerpt_size="30" excludeposts="this" offset="1" thumbnail="yes" thumbnail_size="thumbnail" orderby="date" order="desc"]

**Comment by anykeysolutions** [comment] 2015-09-16 13:07
Same problem here...

As soon as we add the template, only post from the first category are chosen.

[catlist template=SST date=yes orderby=date order=desc  dateformat=d.m.Y name=medienspiegel,pressemitteilung numberposts=5]

**Comment by snookersky** [comment] 2015-09-27 15:00
Same problem here too ...
[catlist id="1,2" excerpt="full" excerpt_strip="no" thumbnail="yes" date="yes" orderby="date" order="desc"] works fine w/o template, but using a template it shows only FIRST category.
Aditional info: get_pagination() in template shows the correct number of pages counted for ALL categories, but the foreach loop ($this->catlist->get_categories_posts()) obviously returns the list only for the FIRST category.

**Comment by snookersky** [comment] 2015-09-27 18:50
It seems that get_categories_posts() doesn't work. As workaround, I succeeded by creating a template replacing the "foreach loop" with the "while loop" found in the build_output() function of the class CatListDisplayer. So a working template would be something like:
`    //Posts loop
    global $post;
    while ( have_posts() ) : the_post();
...
    endwhile;`
I think for someone able to use templates, this hint will lead to the solution of this problem.
Note: the template file is 'required' into the code.

**Comment by picandocodigo** [comment] 2015-09-27 21:28
I haven't been able to reproduce this issue on my dev environment. The function `get_categories_posts()` works fine for me, and I tried reproducing it with several different parameters posted here.

But anyway it might make sense to use `have_posts()` since we changed the loop. This is what the default template would look like. It seems there would be no issue with migrating to this solution. I encourage everyone to test this new code as the template code if possible.

If we find out it's better this way, I'll change it for the next version and document it to see if we can fix general issues with the templates.

Here's the code I changed, any input is more than welcome. Thanks!

```php
<?php
/* This is the string which will gather all the information.*/
$lcp_display_output = '';

// Show category link:
$lcp_display_output .= $this->get_category_link('strong');

// Show the conditional title:
$lcp_display_output .= $this->get_conditional_title();

//Add 'starting' tag. Here, I'm using an unordered list (ul) as an example:
$lcp_display_output .= '<ul class="lcp_catlist">';

global $post;
while ( have_posts() ):
  the_post();

  //Start a List Item for each post:
  $lcp_display_output .= "<li>";

  //Show the title and link to the post:
  $lcp_display_output .= $this->get_post_title($post, 'h3', 'lcp_post');

  //Show comments:
  $lcp_display_output .= $this->get_comments($post);

  //Show date:
  $lcp_display_output .= ' ' . $this->get_date($post);

  //Show date modified:
  $lcp_display_output .= ' ' . $this->get_modified_date($post);

  //Show author
  $lcp_display_output .= $this->get_author($post);

  //Custom fields:
  $lcp_display_output .= $this->get_custom_fields($post);

  //Post Thumbnail
  $lcp_display_output .= $this->get_thumbnail($post);

  /**
   * Post content - Example of how to use tag and class parameters:
   * This will produce:<p class="lcp_content">The content</p>
   */
  $lcp_display_output .= $this->get_content($post, 'p', 'lcp_content');

  /**
   * Post content - Example of how to use tag and class parameters:
   * This will produce:<div class="lcp_excerpt">The content</div>
   */
  $lcp_display_output .= $this->get_excerpt($post, 'div', 'lcp_excerpt');


  // Get Posts "More" link:
  $lcp_display_output .= $this->get_posts_morelink($post);

  //Close li tag
  $lcp_display_output .= '</li>';
endwhile;

// Close the wrapper I opened at the beginning:
$lcp_display_output .= '</ul>';

// If there's a "more link", show it:
$lcp_display_output .= $this->catlist->get_morelink();

//Pagination
$lcp_display_output .= $this->get_pagination();

$this->lcp_output = $lcp_display_output;
```

**Comment by picandocodigo** [comment] 2015-10-08 02:38
@wimstefan @irvingarroyo @anykeysolutions @snookersky Please let me know if you're still having this issue or if I can close it. Thanks.

**Comment by wimstefan** [comment] 2015-10-08 09:21
@picandocodigo Sorry for not coming back to you earlier but I changed my settings in order to have a working site and did not have the time to check whether your changes make it work again. I took some time now!!! And in the short test I did all seems to work so far B-)
Thanks a lot for all your time & efforts!!!

**Comment by picandocodigo** [comment] 2015-10-08 11:59
Thank you for your answer @wimstefan, and thanks for taking the time :smile: 

I'll close the issue in a while if no one else reports problems with this.

**Comment by anykeysolutions** [comment] 2015-10-08 15:55
installed and tested, but the problem still exists. if you use it with a template, only the posts from one category are shown.

**Comment by heidighunter** [comment] 2015-12-17 18:02
I can confirm the same issue with v0.67.1 and WP 4.1.1. I'm using the shortcode as

`[catlist numberposts=-1 pagination=no date=yes template=home-news class=archives id=24,25,85]`

**Comment by anykeysolutions** [comment] 2016-02-03 14:58
Any news on fixing this issue? Problem still exists with WP 4.4.2 and v0.67.1.

**Comment by zymeth25** [comment] 2018-09-04 16:06
Can be closed.

**Closed** 2018-09-04 19:14 UTC
