### ISSUE TITLE
customfield_orderby with customfield_name/customfield_value not working

### ISSUE THREAD

**Issue by Sarah1101** [picandocodigo/List-Category-Posts#243] opened 2017-03-28 07:43 UTC
Hello again,

there is a bug with customfield_orderby.
If I add the parameters customfield_name and customfield_value AND additionally want to add customfield_orderby, the list doesn’t show any results anymore.

Example:
[catlist taxonomy=”customtaxonomy” terms=”customterm1″ customfield_name=”customfield” customfield_value=”0″ customfield_orderby=”orderbyfield” post_status=”any”]

**Comment by picandocodigo** [comment] 2017-03-28 20:53
Thanks I'll look into it asap. Did this start happening with the latest update?

**Comment by Sarah1101** [comment] 2017-03-29 05:45
I'm pretty sure that this happened also before the latest update.

**Comment by picandocodigo** [comment] 2017-03-29 15:21
Ok, thanks! I'll check it out!

**Comment by picandocodigo** [comment] 2017-03-30 03:21
Trying to figure out the issue. If you're getting all posts that have the custom field "customfield" set to value "0", why would you want to order by "customfield" if they all have the same values? Testing without taxonomy and terms it does work for me. I haven't set up any taxonomies on my current testing environment, but let me know if there's an issue there and I'll look deeper into this. Thanks!

**Comment by Sarah1101** [comment] 2017-03-30 07:21
I want to order by another custom field - not the same like "customfield_name".

I've tested a bit, e.g.:
**_Order by the same custom field you filter (but yes, it makes no sense to order by like that)_**
[catlist taxonomy=”customtaxonomy” terms=”customterm1″ customfield_name=”**customfield**” customfield_value=”somevalue″ customfield_orderby=”**customfield**”] => this works 
[catlist taxonomy=”customtaxonomy” terms=”customterm1″ customfield_name=”**customfield**” customfield_value=”somevalue″ customfield_orderby=”**customfield**”] => doesn't work

**_Order by another custom field_**
[catlist taxonomy=”customtaxonomy” terms=”customterm1″ customfield_name=”**customfield**” customfield_value=”somevalue″ customfield_orderby=”**orderbyanothercustomfield**”] => doesn't work
[catlist customfield_name=”**customfield**” customfield_value=”somevalue″ customfield_orderby=”**orderbyanothercustomfield**”] => doesn't work

**Comment by zymeth25** [comment] 2018-02-09 14:02
Duplicate of #261 
Fixed in #273 

Can be closed.

**Closed** 2018-02-12 20:46 UTC
