### ISSUE TITLE
Undefined index: tags_as_class in lcp-widget.php

### ISSUE THREAD

**Issue by hhenshaw** [picandocodigo/List-Category-Posts#231] opened 2017-02-02 11:11 UTC
I'm running 0.71.1 and am getting the following: Notice: Undefined index: tags_as_class in /X/wp-content/plugins/list-category-posts/include/lcp-widget.php on line 40.

**Comment by MatthewEppelsheimer** [comment] 2017-03-03 22:32
I can reproduce this.

**Comment by MatthewEppelsheimer** [comment] 2017-03-03 22:53
This is related to #227 and can use a similar fix. 

However I'd propose to refactor the widget default settings from a series of ternary operators to combining the `$atts` array passed with a `$defaults` array, similar to how `shortcode_atts()` works.

**Comment by vacuus** [comment] 2017-03-03 23:03
I couldn't reproduce this. I think this is an issue with instances created before the tags_as_class feature was created. Changing line 40 to `$tags_as_class = isset($instance['tags_as_class']) ? $instance['tags_as_class'] : 'no';` should provide a temporary fix (might want to sanitize/escape $instance['tags_as_class'] if it does exist).

I think Matthew's suggestion would be the ideal solution.

**Comment by MatthewEppelsheimer** [comment] 2017-03-03 23:05
@vacuus You are correct, this is caused by instances creating before the `tags_as_class` was created. Fairly minor, but hey.

**Comment by MatthewEppelsheimer** [comment] 2017-03-03 23:06
My PR #238 is a quick and dirty fix.

**Comment by picandocodigo** [comment] 2017-03-27 16:24
Just merged @MatthewEppelsheimer's PR, thanks! I'll look into the refactor eventually to improve on this. Thanks everyone!

**Closed** 2017-03-27 16:23 UTC
