### ISSUE TITLE
Issues with a date filter and LCP in index.php

### ISSUE THREAD

**Issue by redweatherday** [picandocodigo/List-Category-Posts#463] opened 2021-05-28 20:02 UTC
### Shortcode used and steps to reproduce the behavior
[catlist template=sw-custom-template-upcoming-walks-widget name=sunday-walks post_status=publish numberposts=5 customfield_compare=walk_date,greaterthanequal,today,DATE customfield_display=walk_grade,walk_distance customfield_display_name=no customfield_display_separately=yes customfield_orderby=walk_date order=asc no_posts_text="To be announced"]
### WP version, LCP plugin version (versions of other software if relevant, e.g. PHP)
WP 5.7.2
LCP 0.84.2

Hi,
The website I manage publishes walks that will take place in the future and provides also an archive of previous walks. In the sidebar I use several text widgets to show future walks, these contain the following (or similar) LCP  shortcode:

[catlist template=sw-custom-template-upcoming-walks-widget name=sunday-walks post_status=publish numberposts=5 customfield_compare=walk_date,greaterthanequal,today,DATE customfield_display=walk_grade,walk_distance customfield_display_name=no customfield_display_separately=yes customfield_orderby=walk_date order=asc no_posts_text="To be announced"]

LCP works just fine on various pages.

The archive of previous walks is actually blog posts filtered by date with this code in my child theme index.php
```php
// Sheffield Walkers Walks Archive Filter Before Today
	    
  function filter_where($where = '') {
      
      $today = date('Y-m-d');
      
        $where .= " AND post_date >= '2018-10-01' AND post_date <= '$today'";
    return $where;
  }
add_filter('posts_where', 'filter_where');
query_posts($query_string);
```
I recently made a few changes and added the LCP shortcode shown above as a text widget in the sidebar of the Previous Walks archive (essentialy the blog posts). Due to the above PHP code in index.php (walks archive / blog, index.php) this prevents future walks displaying in the widget 

I removed the 'filter by date PHP code in index.php' and the LCP shortcode works as expected.

Am I right in thinking this is a result of 'Theme and plugin filters/actions interefering with WP_Query #445' ?

**Comment by klemens-st** [comment] 2021-06-20 14:15
> Am I right in thinking this is a result of 'Theme and plugin filters/actions interfering with WP_Query #445' ?

To an extent yes but this is not what that issue is all about, it is meant to address themes and plugins that add filters on all pages causing certain LCP shortcode parameters to be overridden across all posts.

Here, you add a filter yourself that affects all posts queries on all posts/pages that use the template you modified. This means of course that what you are experiencing is the expected behaviour, not a bug. If you used other plugins that run post queries they would be affected too. 

What I would normally recommend is to add your `posts_where` filter selectively so it only affects the main query but it would not work here because of how certain things are implemented in the LCP plugin (and need to be fixed in the future). First we have to implement what I have already discussed in #445 - something like `main_query=no` so that the plugin does not run main queries itself, you can then set your filters to apply to the main query only and LCP's secondary query will be left clean.

**Comment by redweatherday** [comment] 2021-06-21 09:43
Thank you so much for taking the time to further explain and make reccomendations regarding this issue. I will follow the progress of #455. Meanwhile I will close this issue.
Once again many thanks for a superb plugin.

**Closed** 2021-06-21 09:44 UTC
Labels: enhancement
